In [152]:
#Import required libraries
import pandas as pd
import numpy as np

In [153]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Load Dataset using Pandas Library

In [154]:
df = pd.read_csv("/content/diabetes.csv")
df.head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

Analyze the dataset

In [155]:
print("Dataset Shape:")
print(df.shape)

Dataset Shape:
(768, 9)

In [156]:
print("Name of Columns:")
print(df.columns)

Name of Columns:
Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [157]:
print("Data Types:")
print(df.dtypes)

Data Types:
Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [158]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [159]:
print("Summary of Dataset:")
df.describe()

Summary of Dataset:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

Separate Dataset into features and target variables

In [160]:
# Features
X = df.drop("Outcome", axis=1)

# Target
y = df["Outcome"]

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

Feature Shape: (768, 8)
Target Shape: (768,)

In [161]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training dataset (features):", X_train.shape)
print("Training dataset (labels):", y_train.shape)
print("Testing dataset (features):", X_test.shape)
print("Testing dataset (labels):", y_test.shape)

Training dataset (features): (614, 8)
Training dataset (labels): (614,)
Testing dataset (features): (154, 8)
Testing dataset (labels): (154,)

Apply feature scaling using StandardScaler

In [162]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [163]:
print("First five rows of the standardized training dataset:")
print(X_train_scaled[:5])

print("\nFirst five rows of the standardized testing dataset:")
print(X_test_scaled[:5])

First five rows of the standardized training dataset:
[[-0.52639686 -1.15139792 -3.75268255 -1.32277365 -0.70120553 -4.13525578
  -0.49073479 -1.03594038]
 [ 1.58804586 -0.27664283  0.68034485  0.23350519 -0.70120553 -0.48916881
   2.41502991  1.48710085]
 [-0.82846011  0.56687102 -1.2658623  -0.09071957  0.01344832 -0.42452187
   0.54916055 -0.94893896]
 [-1.13052335  1.2541786  -1.04961706 -1.32277365 -0.70120553 -1.30372015
  -0.63929127  2.79212217]
 [ 0.68185612  0.41066475  0.57222224  1.07648956  2.48460077  1.83812075
  -0.68682934  1.13909516]]

First five rows of the standardized testing dataset:
[[ 0.68185612 -0.71402038 -0.61712658  0.81710976  0.93474906  0.26073561
  -0.11637247  0.87809089]
 [-0.52639686 -0.27664283  0.30191569  0.7522648  -0.70120553  0.48053518
  -0.954231   -1.03594038]
 [-0.52639686 -0.40160784 -0.29275872 -1.32277365 -0.70120553 -0.15300476
  -0.9245197  -1.03594038]
 [ 1.28598261 -0.43284909  0.57222224 -1.32277365 -0.70120553 -0.95462672
   1.14932872  0.0950781 ]
 [ 0.98391937  0.47314726  1.11283533 -1.32277365 -0.70120553 -0.26936924
  -0.77002097  1.48710085]]

**PART 2** - Building ANN

In [164]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, InputLayer

In [165]:
# Build a sequential neural network for diabetes prediction
model = Sequential([
    layers.Input(shape=(X_train_scaled.shape[1],), name="input_layer"),  # Accepts all input features from the processed dataset
    layers.Dense(units=64, activation='relu', name="hiddenlayer_1"),     # First hidden layer with 32 neurons using ReLU activation
    layers.Dense(units=32, activation='relu', name="hiddenlayer_2"),     # Second hidden layer with 16 neurons to learn deeper patterns
    layers.Dense(units=1, activation='sigmoid', name="output_layer")     # Produces the probability of the positive class
])

In [166]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [167]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ hiddenlayer_1 (Dense)           │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hiddenlayer_2 (Dense)           │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_layer (Dense)            │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,689 (10.50 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

**Part 3 - Training the Model**

In [168]:
# Train the ANN model

history = model.fit(
    X_train_scaled,
    y_train,
    epochs=300,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - accuracy: 0.6599 - loss: 0.6548 - val_accuracy: 0.6341 - val_loss: 0.6577
Epoch 2/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6864 - loss: 0.5920 - val_accuracy: 0.6748 - val_loss: 0.6012
Epoch 3/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7189 - loss: 0.5427 - val_accuracy: 0.6911 - val_loss: 0.5577
Epoch 4/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7576 - loss: 0.5060 - val_accuracy: 0.7073 - val_loss: 0.5291
Epoch 5/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7699 - loss: 0.4823 - val_accuracy: 0.7317 - val_loss: 0.5086
Epoch 6/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7923 - loss: 0.4651 - val_accuracy: 0.7480 - val_loss: 0.4897
Epoch 7/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7821 - loss: 0.4539 - val_accuracy: 0.7398 - val_loss: 0.4851
Epoch 8/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7882 - loss: 0.4451 - val_accuracy: 0.7480 - val_loss: 0.4775
Epoch 9/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7943 - loss: 0.4390 - val_accuracy: 0.7561 - val_loss: 0.4767
Epoch 10/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7943 - loss: 0.4348 - val_accuracy: 0.7561 - val_loss: 0.4753
Epoch 11/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7963 - loss: 0.4296 - val_accuracy: 0.7480 - val_loss: 0.4770
Epoch 12/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7902 - loss: 0.4295 - val_accuracy: 0.7480 - val_loss: 0.4717
Epoch 13/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8004 - loss: 0.4226 - val_accuracy: 0.7398 - val_loss: 0.4740
Epoch 14/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7963 - loss: 0.4210 - val_accuracy: 0.7398 - val_loss: 0.4725
Epoch 15/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8045 - loss: 0.4153 - val_accuracy: 0.7398 - val_loss: 0.4710
Epoch 16/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8045 - loss: 0.4129 - val_accuracy: 0.7480 - val_loss: 0.4719
Epoch 17/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8004 - loss: 0.4107 - val_accuracy: 0.7561 - val_loss: 0.4671
Epoch 18/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8045 - loss: 0.4072 - val_accuracy: 0.7480 - val_loss: 0.4694
Epoch 19/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8086 - loss: 0.4043 - val_accuracy: 0.7642 - val_loss: 0.4669
Epoch 20/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8086 - loss: 0.4022 - val_accuracy: 0.7724 - val_loss: 0.4680
Epoch 21/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8086 - loss: 0.4014 - val_accuracy: 0.7724 - val_loss: 0.4653
Epoch 22/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8126 - loss: 0.3979 - val_accuracy: 0.7724 - val_loss: 0.4666
Epoch 23/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8126 - loss: 0.3982 - val_accuracy: 0.7724 - val_loss: 0.4650
Epoch 24/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8187 - loss: 0.3932 - val_accuracy: 0.7724 - val_loss: 0.4662
Epoch 25/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8086 - loss: 0.3926 - val_accuracy: 0.7724 - val_loss: 0.4671
Epoch 26/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8126 - loss: 0.3900 - val_accuracy: 0.7724 - val_loss: 0.4606
Epoch 27/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8228 - loss: 0.3876 - val_accuracy: 0.7724 - val_loss: 0.4581
Epoch 28/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8208 - loss: 0.3872 - val_accuracy: 0.7724 - val_loss: 0.4604
Epoch 29/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8187 - loss: 0.3845 - val_accuracy: 0.7724 - val_loss: 0.4614
Epoch 30/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8228 - loss: 0.3818 - val_accuracy: 0.7724 - val_loss: 0.4626
Epoch 31/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8269 - loss: 0.3790 - val_accuracy: 0.7724 - val_loss: 0.4600
Epoch 32/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8248 - loss: 0.3787 - val_accuracy: 0.7724 - val_loss: 0.4564
Epoch 33/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8208 - loss: 0.3765 - val_accuracy: 0.7724 - val_loss: 0.4607
Epoch 34/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8248 - loss: 0.3757 - val_accuracy: 0.7724 - val_loss: 0.4633
Epoch 35/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8248 - loss: 0.3729 - val_accuracy: 0.7724 - val_loss: 0.4633
Epoch 36/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8269 - loss: 0.3727 - val_accuracy: 0.7724 - val_loss: 0.4619
Epoch 37/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8330 - loss: 0.3710 - val_accuracy: 0.7724 - val_loss: 0.4662
Epoch 38/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8269 - loss: 0.3688 - val_accuracy: 0.7724 - val_loss: 0.4711
Epoch 39/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8310 - loss: 0.3654 - val_accuracy: 0.7724 - val_loss: 0.4659
Epoch 40/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8310 - loss: 0.3634 - val_accuracy: 0.7642 - val_loss: 0.4569
Epoch 41/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8310 - loss: 0.3638 - val_accuracy: 0.7724 - val_loss: 0.4643
Epoch 42/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8310 - loss: 0.3602 - val_accuracy: 0.7642 - val_loss: 0.4562
Epoch 43/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8208 - loss: 0.3602 - val_accuracy: 0.7724 - val_loss: 0.4629
Epoch 44/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8411 - loss: 0.3575 - val_accuracy: 0.7724 - val_loss: 0.4622
Epoch 45/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8411 - loss: 0.3571 - val_accuracy: 0.7724 - val_loss: 0.4614
Epoch 46/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8391 - loss: 0.3547 - val_accuracy: 0.7724 - val_loss: 0.4599
Epoch 47/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8432 - loss: 0.3516 - val_accuracy: 0.7724 - val_loss: 0.4578
Epoch 48/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8452 - loss: 0.3497 - val_accuracy: 0.7724 - val_loss: 0.4650
Epoch 49/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8452 - loss: 0.3490 - val_accuracy: 0.7724 - val_loss: 0.4634
Epoch 50/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8473 - loss: 0.3473 - val_accuracy: 0.7724 - val_loss: 0.4630
Epoch 51/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8473 - loss: 0.3459 - val_accuracy: 0.7724 - val_loss: 0.4667
Epoch 52/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8432 - loss: 0.3426 - val_accuracy: 0.7642 - val_loss: 0.4660
Epoch 53/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8493 - loss: 0.3411 - val_accuracy: 0.7642 - val_loss: 0.4658
Epoch 54/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8554 - loss: 0.3400 - val_accuracy: 0.7642 - val_loss: 0.4711
Epoch 55/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8554 - loss: 0.3388 - val_accuracy: 0.7724 - val_loss: 0.4689
Epoch 56/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8554 - loss: 0.3350 - val_accuracy: 0.7724 - val_loss: 0.4632
Epoch 57/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8513 - loss: 0.3339 - val_accuracy: 0.7642 - val_loss: 0.4693
Epoch 58/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8554 - loss: 0.3333 - val_accuracy: 0.7724 - val_loss: 0.4724
Epoch 59/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8676 - loss: 0.3315 - val_accuracy: 0.7724 - val_loss: 0.4705
Epoch 60/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8635 - loss: 0.3317 - val_accuracy: 0.7642 - val_loss: 0.4649
Epoch 61/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8676 - loss: 0.3272 - val_accuracy: 0.7724 - val_loss: 0.4679
Epoch 62/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8656 - loss: 0.3251 - val_accuracy: 0.7642 - val_loss: 0.4681
Epoch 63/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8697 - loss: 0.3235 - val_accuracy: 0.7642 - val_loss: 0.4719
Epoch 64/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3219 - val_accuracy: 0.7724 - val_loss: 0.4720
Epoch 65/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8635 - loss: 0.3248 - val_accuracy: 0.7561 - val_loss: 0.4777
Epoch 66/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8676 - loss: 0.3184 - val_accuracy: 0.7398 - val_loss: 0.4819
Epoch 67/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8758 - loss: 0.3149 - val_accuracy: 0.7642 - val_loss: 0.4800
Epoch 68/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8758 - loss: 0.3149 - val_accuracy: 0.7561 - val_loss: 0.4789
Epoch 69/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8615 - loss: 0.3169 - val_accuracy: 0.7561 - val_loss: 0.4855
Epoch 70/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8717 - loss: 0.3145 - val_accuracy: 0.7561 - val_loss: 0.4741
Epoch 71/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3113 - val_accuracy: 0.7561 - val_loss: 0.4771
Epoch 72/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8778 - loss: 0.3088 - val_accuracy: 0.7561 - val_loss: 0.4859
Epoch 73/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8758 - loss: 0.3070 - val_accuracy: 0.7642 - val_loss: 0.4823
Epoch 74/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8880 - loss: 0.3053 - val_accuracy: 0.7642 - val_loss: 0.4812
Epoch 75/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8839 - loss: 0.3029 - val_accuracy: 0.7642 - val_loss: 0.4882
Epoch 76/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8900 - loss: 0.3008 - val_accuracy: 0.7561 - val_loss: 0.4828
Epoch 77/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8758 - loss: 0.2999 - val_accuracy: 0.7561 - val_loss: 0.4882
Epoch 78/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8859 - loss: 0.2965 - val_accuracy: 0.7480 - val_loss: 0.4876
Epoch 79/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8880 - loss: 0.2942 - val_accuracy: 0.7480 - val_loss: 0.4873
Epoch 80/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8839 - loss: 0.2937 - val_accuracy: 0.7561 - val_loss: 0.4880
Epoch 81/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8839 - loss: 0.2909 - val_accuracy: 0.7480 - val_loss: 0.4904
Epoch 82/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8900 - loss: 0.2887 - val_accuracy: 0.7480 - val_loss: 0.4955
Epoch 83/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8819 - loss: 0.2887 - val_accuracy: 0.7561 - val_loss: 0.4936
Epoch 84/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8839 - loss: 0.2879 - val_accuracy: 0.7480 - val_loss: 0.4929
Epoch 85/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8921 - loss: 0.2830 - val_accuracy: 0.7642 - val_loss: 0.4964
Epoch 86/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8880 - loss: 0.2811 - val_accuracy: 0.7480 - val_loss: 0.4950
Epoch 87/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8921 - loss: 0.2809 - val_accuracy: 0.7561 - val_loss: 0.4923
Epoch 88/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8921 - loss: 0.2793 - val_accuracy: 0.7642 - val_loss: 0.4956
Epoch 89/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8982 - loss: 0.2775 - val_accuracy: 0.7561 - val_loss: 0.5043
Epoch 90/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8941 - loss: 0.2747 - val_accuracy: 0.7480 - val_loss: 0.4911
Epoch 91/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8819 - loss: 0.2737 - val_accuracy: 0.7561 - val_loss: 0.5020
Epoch 92/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8982 - loss: 0.2723 - val_accuracy: 0.7561 - val_loss: 0.5067
Epoch 93/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8961 - loss: 0.2666 - val_accuracy: 0.7480 - val_loss: 0.4955
Epoch 94/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8819 - loss: 0.2721 - val_accuracy: 0.7561 - val_loss: 0.5064
Epoch 95/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8900 - loss: 0.2675 - val_accuracy: 0.7398 - val_loss: 0.4987
Epoch 96/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9022 - loss: 0.2668 - val_accuracy: 0.7561 - val_loss: 0.5112
Epoch 97/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8982 - loss: 0.2669 - val_accuracy: 0.7561 - val_loss: 0.4973
Epoch 98/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9104 - loss: 0.2614 - val_accuracy: 0.7398 - val_loss: 0.4992
Epoch 99/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9063 - loss: 0.2586 - val_accuracy: 0.7480 - val_loss: 0.5126
Epoch 100/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8982 - loss: 0.2651 - val_accuracy: 0.7480 - val_loss: 0.5076
Epoch 101/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9043 - loss: 0.2571 - val_accuracy: 0.7561 - val_loss: 0.5157
Epoch 102/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8941 - loss: 0.2560 - val_accuracy: 0.7480 - val_loss: 0.5100
Epoch 103/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9022 - loss: 0.2532 - val_accuracy: 0.7398 - val_loss: 0.5111
Epoch 104/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9063 - loss: 0.2546 - val_accuracy: 0.7480 - val_loss: 0.5071
Epoch 105/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9124 - loss: 0.2485 - val_accuracy: 0.7480 - val_loss: 0.5062
Epoch 106/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9165 - loss: 0.2480 - val_accuracy: 0.7561 - val_loss: 0.5216
Epoch 107/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9084 - loss: 0.2463 - val_accuracy: 0.7480 - val_loss: 0.5144
Epoch 108/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9043 - loss: 0.2442 - val_accuracy: 0.7398 - val_loss: 0.5196
Epoch 109/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9124 - loss: 0.2425 - val_accuracy: 0.7398 - val_loss: 0.5234
Epoch 110/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9145 - loss: 0.2408 - val_accuracy: 0.7398 - val_loss: 0.5246
Epoch 111/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9104 - loss: 0.2437 - val_accuracy: 0.7480 - val_loss: 0.5309
Epoch 112/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9165 - loss: 0.2375 - val_accuracy: 0.7398 - val_loss: 0.5322
Epoch 113/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9206 - loss: 0.2362 - val_accuracy: 0.7398 - val_loss: 0.5247
Epoch 114/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9124 - loss: 0.2374 - val_accuracy: 0.7561 - val_loss: 0.5265
Epoch 115/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9185 - loss: 0.2378 - val_accuracy: 0.7480 - val_loss: 0.5369
Epoch 116/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9145 - loss: 0.2293 - val_accuracy: 0.7480 - val_loss: 0.5291
Epoch 117/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9165 - loss: 0.2317 - val_accuracy: 0.7398 - val_loss: 0.5358
Epoch 118/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9145 - loss: 0.2270 - val_accuracy: 0.7398 - val_loss: 0.5359
Epoch 119/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9308 - loss: 0.2291 - val_accuracy: 0.7561 - val_loss: 0.5396
Epoch 120/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9165 - loss: 0.2256 - val_accuracy: 0.7398 - val_loss: 0.5405
Epoch 121/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9124 - loss: 0.2265 - val_accuracy: 0.7398 - val_loss: 0.5374
Epoch 122/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9246 - loss: 0.2203 - val_accuracy: 0.7561 - val_loss: 0.5415
Epoch 123/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9185 - loss: 0.2174 - val_accuracy: 0.7398 - val_loss: 0.5616
Epoch 124/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9246 - loss: 0.2246 - val_accuracy: 0.7480 - val_loss: 0.5483
Epoch 125/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9328 - loss: 0.2176 - val_accuracy: 0.7480 - val_loss: 0.5584
Epoch 126/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9084 - loss: 0.2248 - val_accuracy: 0.7642 - val_loss: 0.5492
Epoch 127/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9348 - loss: 0.2155 - val_accuracy: 0.7480 - val_loss: 0.5572
Epoch 128/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9267 - loss: 0.2104 - val_accuracy: 0.7480 - val_loss: 0.5483
Epoch 129/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9348 - loss: 0.2095 - val_accuracy: 0.7398 - val_loss: 0.5627
Epoch 130/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9165 - loss: 0.2089 - val_accuracy: 0.7480 - val_loss: 0.5564
Epoch 131/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9348 - loss: 0.2107 - val_accuracy: 0.7642 - val_loss: 0.5738
Epoch 132/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9246 - loss: 0.2088 - val_accuracy: 0.7561 - val_loss: 0.5575
Epoch 133/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9328 - loss: 0.2031 - val_accuracy: 0.7480 - val_loss: 0.5639
Epoch 134/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9287 - loss: 0.2012 - val_accuracy: 0.7480 - val_loss: 0.5625
Epoch 135/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9308 - loss: 0.2009 - val_accuracy: 0.7561 - val_loss: 0.5753
Epoch 136/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9348 - loss: 0.1990 - val_accuracy: 0.7480 - val_loss: 0.5829
Epoch 137/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9328 - loss: 0.1950 - val_accuracy: 0.7480 - val_loss: 0.5642
Epoch 138/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9328 - loss: 0.1942 - val_accuracy: 0.7480 - val_loss: 0.5777
Epoch 139/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9389 - loss: 0.1947 - val_accuracy: 0.7480 - val_loss: 0.5800
Epoch 140/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9267 - loss: 0.1935 - val_accuracy: 0.7561 - val_loss: 0.5818
Epoch 141/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9328 - loss: 0.1905 - val_accuracy: 0.7561 - val_loss: 0.5786
Epoch 142/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9369 - loss: 0.1909 - val_accuracy: 0.7398 - val_loss: 0.5859
Epoch 143/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9246 - loss: 0.1891 - val_accuracy: 0.7642 - val_loss: 0.5772
Epoch 144/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9409 - loss: 0.1864 - val_accuracy: 0.7480 - val_loss: 0.5938
Epoch 145/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9409 - loss: 0.1859 - val_accuracy: 0.7480 - val_loss: 0.5939
Epoch 146/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9328 - loss: 0.1931 - val_accuracy: 0.7561 - val_loss: 0.5750
Epoch 147/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9430 - loss: 0.1841 - val_accuracy: 0.7480 - val_loss: 0.5999
Epoch 148/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9409 - loss: 0.1824 - val_accuracy: 0.7480 - val_loss: 0.5998
Epoch 149/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9511 - loss: 0.1781 - val_accuracy: 0.7480 - val_loss: 0.6002
Epoch 150/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9450 - loss: 0.1796 - val_accuracy: 0.7480 - val_loss: 0.5860
Epoch 151/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9409 - loss: 0.1819 - val_accuracy: 0.7561 - val_loss: 0.6094
Epoch 152/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9470 - loss: 0.1796 - val_accuracy: 0.7480 - val_loss: 0.6008
Epoch 153/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9470 - loss: 0.1748 - val_accuracy: 0.7642 - val_loss: 0.5914
Epoch 154/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9552 - loss: 0.1740 - val_accuracy: 0.7561 - val_loss: 0.5986
Epoch 155/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9511 - loss: 0.1697 - val_accuracy: 0.7480 - val_loss: 0.6073
Epoch 156/300

In [179]:
# Calculate the accuracy achieved at the end of training
final_accuracy = history.history['accuracy'][-1]

print("Training accuracy acheived by the Model:", round(final_accuracy * 100, 2), "%")

Training accuracy acheived by the Model: 100.0 %

In [170]:
print("Total epochs executed:", len(history.history['accuracy']))

Total epochs executed: 300

**Part 4 - Model Evaluation**

In [171]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [172]:
# Obtain probability scores for each test instance
y_pred_prob = model.predict(X_test_scaled)

# Display the predicted probabilities of the first five instances
print(y_pred_prob[:5])

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.4713235 ]
 [0.04025404]
 [0.0008943 ]
 [0.17844182]
 [0.0509356 ]]

In [173]:
# Classify each prediction based on a 0.5 decision threshold
y_pred = (y_pred_prob >= 0.5).astype(int)

In [174]:
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", round(accuracy * 100, 2), "%")

Model Accuracy: 74.03 %

In [175]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[80 19]
 [21 34]]

In [180]:
import pandas as pd

cm_df = pd.DataFrame(
    cm,
    index=["True Class:No Diabetes", "True Class:Diabetes"],
    columns=["Model Prediction:No Diabetes", "Model Prediction:Diabetes"]
)

cm_df

,Model Prediction:No Diabetes,Model Prediction:Diabetes
True Class:No Diabetes,80,19
True Class:Diabetes,21,34

## Confusion Matrix Summary

The confusion matrix indicates that the model performed well in distinguishing between diabetic and non-diabetic patients.
* Out of 99 patients who did not have diabetes, the model correctly classified 80 as non-diabetic, while 19 were incorrectly predicted as diabetic (false positives).
* Similarly, among 55 patients with diabetes, the model correctly identified 34 cases, whereas 21 diabetic patients were incorrectly classified as non-diabetic (false negatives).

Overall, the model made 114 correct predictions out of 154 test samples, corresponding to an accuracy of approximately 74%. The results show that the model is more effective at identifying patients without diabetes than detecting those with diabetes. Reducing the number of false negatives would further improve the model, as missed diabetes cases can have important clinical implications.